const products = [
    {   id:1,
        title:"Notebook AMD Athlon HP 14-DK1015LA",
        description:"Esta computadora portátil delgada y ultraportátil ofrece un rendimiento confiable. Gracias a la batería de larga duración, es fácil mantenerse sociable, productivo y conectado a lo que importa. La pantalla con microborde le brinda mucho para ver con la mayor imagen posible en un marco más pequeño",
        category:"hogar",
        price:315,
        pictureUrl:"/images/hogar-1.png" }
        ,
    {   id:2,
        title:"Laptop ci5 ASUS TUF F506LH",
        description:"A pesar de contar con un chasis mas péqueño y liivnao que sus predecesores, el F15 alberga una batería más grande para una vida más larga. Las pruebas de caída aseguran que cada ",
        category:"hogar",
        price:1070,
        pictureUrl:"/images/hogar-2.png"},
    {   id:3,
        title:"Laptop ci3 DELL 8/s256/15.6/free",
        description:"Laptop de 15 pulgadas que ofrece un rendimieno con capacidad de respuesta en un diseño elegante con bordes angostos de dos lados, cuenta con un almacenamiento SSD 256GB M.2 NV;e, ExpressCharge, y procesador Intel Core",
        category:"hogar",
        price: 560,
        pictureUrl:"/images/hogar-3.png"},        
    {   id:4,
        title:"Laptop WS Ci7 MSI WF65 10TI 16/512+1/15.6/VDQ4w10",
        description:"",
        category:"empresa",
        price:1000,
        pictureUrl:"/images/empresa-1.png" }
        ,
    {   id:5,
        title:"Computadora Lenovo",
        description:"IdeaCentre AIO 3i Intel Core i3 23.8\" Full HD 1TB + 128GB SSD 4GB RAM Business Black",
        category:"empresa",
        price:800,
        pictureUrl:"/images/empresa-2.png"},
    {   id:6,
        title:"Impresora Epson",
        description:"Impresora Multifuncional EcoTank L3110 Epson",
        category:"empresa",
        price: 250,
        pictureUrl:"/images/empresa-3.png"},
    {   id:7,
        title:"Laptop ASUS",
        description:"VivoBook 15 K513 Core i7 11a 15.6'' FHD IPS 512GB SSD 8GB RAM",
        category:"gamer",
        price:1000,
        pictureUrl:"/images/gamer-1.png" }
        ,
    {   id:8,
        title:"Computadora Lenovo",
        description:"IdeaCentre AIO 3i Intel Core i3 23.8\" Full HD 1TB + 128GB SSD 4GB RAM Business Black",
        category:"gamer",
        price:800,
        pictureUrl:"/images/gamer-2.png"},
    {   id:9,
        title:"Impresora Epson",
        description:"Impresora Multifuncional EcoTank L3110 Epson",
        category:"gamer",
        price: 250,
        pictureUrl:"/images/gamer-3.png"}                            
 ]

export const getFetch = new Promise( (resolve) => {        
    setTimeout(()=> {
        resolve(products)
    },3000)
})