const products = [
    {   id:1,
        title:"Laptop ASUS",
        description:"VivoBook 15 K513 Core i7 11a 15.6'' FHD IPS 512GB SSD 8GB RAM",
        category:"hogar",
        price:1000,
        pictureUrl:"/images/hogar-1.png" }
        ,
    {   id:2,
        title:"Computadora Lenovo",
        description:"IdeaCentre AIO 3i Intel Core i3 23.8\" Full HD 1TB + 128GB SSD 4GB RAM Business Black",
        category:"hogar",
        price:800,
        pictureUrl:"/images/hogar-2.png"},
    {   id:3,
        title:"Impresora Epson",
        description:"Impresora Multifuncional EcoTank L3110 Epson",
        category:"hogar",
        price: 250,
        pictureUrl:"/images/hogar-3.png"},        
    {   id:4,
        title:"Laptop ASUS",
        description:"VivoBook 15 K513 Core i7 11a 15.6'' FHD IPS 512GB SSD 8GB RAM",
        category:"empresa",
        price:1000,
        pictureUrl:"/images/empresa-1.png" }
        ,
    {   id:5,
        title:"Computadora Lenovo",
        description:"IdeaCentre AIO 3i Intel Core i3 23.8\" Full HD 1TB + 128GB SSD 4GB RAM Business Black",
        category:"empresa",
        price:800,
        pictureUrl:"/images/empresa-2.png"},
    {   id:6,
        title:"Impresora Epson",
        description:"Impresora Multifuncional EcoTank L3110 Epson",
        category:"empresa",
        price: 250,
        pictureUrl:"/images/empresa-3.png"},
    {   id:7,
        title:"Laptop ASUS",
        description:"VivoBook 15 K513 Core i7 11a 15.6'' FHD IPS 512GB SSD 8GB RAM",
        category:"gamer",
        price:1000,
        pictureUrl:"/images/gamer-1.png" }
        ,
    {   id:8,
        title:"Computadora Lenovo",
        description:"IdeaCentre AIO 3i Intel Core i3 23.8\" Full HD 1TB + 128GB SSD 4GB RAM Business Black",
        category:"gamer",
        price:800,
        pictureUrl:"/images/gamer-2.png"},
    {   id:9,
        title:"Impresora Epson",
        description:"Impresora Multifuncional EcoTank L3110 Epson",
        category:"gamer",
        price: 250,
        pictureUrl:"/images/gamer-3.png"}                            
 ]

export const getFetch = new Promise( (resolve) => {        
    setTimeout(()=> {
        resolve(products)
    },3000)
})